const en = {
    sign_in: "Sign In",
    sign_up: "Sign Up",
    first_name: "First Name",
    last_name: "Last Name",
    email: "Email",
    password: "Password",
    welcome: "Welcome to",
    change_language: "Change Language",
    forgot_password: "Forgot Password?",
    forgot_password_no_question_mark: "Forgot Password",
    do_not_have_an_account: "Don't have an account? Sign up",
    back: "Back",
    valid_address: "Please enter a valid email address",
    confirm_password: "Confirm Password",
    next: "Next",
    street_address: "Street Address",
    postal_code: "Postal Code",
    verify_address: "Verify Address",
    already_have_an_account:"Already have an account? Sign in",
    valid_address_entered:"Valid Address entered",
    send_reset_pin: "Send Reset PIN",
    enter_pin: "Enter PIN",
    Check_email_for_PIN:"Check your email for a PIN to reset your password",
    home_screen: "Home Screen",
    in_progress: "In Progress",
    completed: "Completed",
    jobs_available: "No jobs available",
    my_issues: "My Issues",
    mission: 'Jobs',
    create_issue: "Create Issue",
    logout: "Logout",
    describe_your_service: "Describe your service",
    select_type: "Select Type",
    plumbing: "Plumbing",
    electrical: "Electrical",
    low_priority: "Low Priority",
    high_priority: "High Priority",
    location:"Location",
    enter_location:"Enter Location",
}

const fr = {
    sign_in: "Se connecter",
    sign_up: "S'inscrire",
    first_name: "Prénom",
    last_name: "Nom de Famille",
    email: "Courriel",
    password: "Mot de Passe",
    welcome: "Bienvenue à",
    change_language: "Changer La Langue",
    forgot_password: "Oubli du mot de passe?",
    forgot_password_no_question_mark: "Mot de passe oublié",
    do_not_have_an_account: "Si vous n'avez pas encore de compte, créez-en un",
    back: "Retourner",
    valid_address:"Veuillez indiquer une adresse de courriel valide",
    confirm_password: "Confirmer le mot de passe",
    next: "Suivant",
    street_address: "Adresse Civique",
    postal_code: "Code Postal",
    verify_address: "Vérifier l'adresse",
    already_have_an_account:"Vous êtes déjà inscrit? Se connecter",
    valid_address_entered:"Une adresse de courriel valide",
    send_reset_pin: "Rétablissez le PIN",
    enter_pin:"Entrer un code PIN",
    Check_email_for_PIN:"Consultez votre courrier électronique pour obtenir un code PIN",
    home_screen: "Accueil",
    in_progress: "en cours",
    completed: "Terminé",
    jobs_available: "pas des travail libres",
    my_issues: "Mes Tâches",
    mission:'mission',
    create_issue: "Créer une tache",
    logout:"Déconnexion",
    describe_your_service: "Décrivez votre service",
    select_type:"Choisissez une catégorie",
    plumbing: "Plomberie",
    electrical: "Électrique",
    low_priority: "faible priorité",
    high_priority: "haute priorité",
    location:"Site",
    enter_location:"Entrez un emplacement",
}

export {en, fr}