const en = {
    sign_in: "Sign In",
    sign_up: "Sign Up",
    first_name: "First Name",
    last_name: "Last Name",
    email: "Email",
    password: "Password",
    welcome: "Welcome to",
    change_language: "Change Language",
    forgot_password: "Forgot Password?",
    forgot_password_no_question_mark: "Forgot Password",
    do_not_have_an_account: "Don't have an account? Sign up",
    back: "Back",
    valid_address: "Please enter a valid email address",
    confirm_password: "Confirm Password",
    next: "Next",
    street_address: "Street Address",
    postal_code: "Postal Code",
    verify_address: "Verify Address",
    already_have_an_account:"Already have an account? Sign in",
    valid_address_entered:"Valid Address entered",
    send_reset_pin: "Send Reset PIN",
    enter_pin: "Enter PIN",
    Check_email_for_PIN:"Check your email for a PIN to reset your password",
    home_screen: "Home Screen",
    home: "Home",
    in_progress: "In Progress",
    completed: "Completed",
    jobs_available: "No jobs available",
    my_jobs: "My Jobs",
    mission: 'Jobs',
    create_job: "Create New Job",
    logout: "Logout",
    describe_your_service: "Describe your service",
    select_service_type: "Select Service Type(s)",
    select_service: "Select Service",
    select_timeline:"Select Timeline",
    plumbing: "Plumbing",
    electrical: "Electrical",
    low_priority: "Low Priority",
    high_priority: "High Priority",
    location:"Location",
    enter_location:"Enter Location",
    signed_in_successfully:"Signed in successfully",
    error:"Error",
    an_unexpected_error_occurred: "An unexpected error occurred",
    please_verify_your_email_before_logging_in: "Please verify your email before logging in",
    take_from_your_gallery: "Take from your gallery",
    job_description:"Job Description",
    job_posted_successfully: "Job posted successfully",
    modify_issue: "Modify Issue",
    delete_issue: "Delete Issue",
    logged_out: "Logged out",
    you_have_been_logged_out_successfully:"you have successfully logged out successfully",
    an_error_occurred_while_logging_out:"an error occurred while logging out",
    hi:"Hi",
    need_something:"Need Something",
    fixed:"fixed?",
    categories:"Categories",
    view_all: "View All",
    cleaning:"Cleaning",
    requests:"Requests",
    accept:"Accept",
    reject:"Reject",
    professional_needed:"Professional Needed",
    created_on:"Created On",
    status:"Status",
    cancel:"Cancel",
    status_client: {
        open: "Open",
        closed: "Closed",
        "closed by client": "Closed By Client",
        completed: "Completed",
        pending: "Pending",
        reopened: "Reopened",
        "in progress": "In Progress",
    },
    attached_images: "Attached Images",
    no_image_attached: "No image attached yet",
    assigned_professional: "Assigned Professional",
    rating: "Rating",
    comment: "Comment",
    review: "Review",
    no_description_provided:"No description provided",
    payment_method: "Payment Method",
    visa_ending: "Visa ending in",
    language: "Language",
    title: "Title",
    image: "Image",
    badges_remaining: "You can select {{count}} more",
    your_job_has_been_posted: "Congrats! Your job has been posted!",
    use_default_address: "Use Default Address",
    enter_new_address: "Enter New Location",
    posting_your_job: "Posting your job...",
    reopen: "reopen",
    delete: "delete",
    are_you_sure: "Are you sure you want to",
    this_issue: "this issue?",
    modify_issue_text: "This will clone this issue and create a new one. You can find it under your open issues.",
    yes: "Yes",
    jobInProgressComment: "This issue is currently in progress. For any changes or updates, please reach out to the professional assigned using the chat feature." ,
    no_requests_available: "No offers for your tasks yet.",
    select_language: "Select Language",
    select_language_prompt: "Please select your preferred language:",
    settings:'Settings',
    edit_profile:'Edit Profile',
    appearance:'Appearance',
    terms_and_conditions:'Terms and Conditions',
    coming_soon: 'Coming Soon',
    appearance_feature_message: 'This feature is in progress! You will be able to choose between light and dark mode!',
    profile:'Profile',
    street:'Street:',
    current_password: 'Current Password',
    current_password_validated:'Current password validated. You can now set a new password.',
    new_password:'New Password',
    validate:'Validate',
    save_changes:'Save Changes',
    authentication_failed:'Authentication failed.',
    profile_data_failed_loading:'Failed to load profile data.',
    success:"Success",
    invalid_address:'Invalid address. Please enter a valid address.',
    address_verified_successfully:'Address verified successfully.',
    incorrect_password:'Incorrect password',
    network_error:'Network error. Please check your connection and try again.',
    new_passwords_match_error:'New passwords do not match.',
    validate_password_please:'Please validate your current password before updating.',
    changes_saved:'Your changes have been saved.',
    profile_update_error:'Failed to update profile.',
    new_passwords_match:'Passwords match ✓',
    new_passwords_mismatch:"Passwords don't match ✗",
    current_password_error:'Current password is incorrect.'
}

const fr = {
    sign_in: "Se connecter",
    sign_up: "S'inscrire",
    first_name: "Prénom",
    last_name: "Nom de Famille",
    email: "Courriel",
    password: "Mot de Passe",
    welcome: "Bienvenue",
    change_language: "Changer La Langue",
    forgot_password: "Oublié votre mot de passe?",
    forgot_password_no_question_mark: "Mot de passe oublié",
    do_not_have_an_account: "Si vous n'avez pas encore de compte, créez-en un",
    back: "Retourner",
    valid_address:"Veuillez indiquer une adresse de courriel valide",
    confirm_password: "Confirmer le mot de passe",
    next: "Suivant",
    street_address: "Adresse Civique",
    postal_code: "Code Postal",
    verify_address: "Vérifier l'adresse",
    already_have_an_account:"Vous êtes déjà inscrit? Se connecter",
    valid_address_entered:"Une adresse de courriel valide",
    send_reset_pin: "Rétablissez le PIN",
    enter_pin:"Entrer un code PIN",
    Check_email_for_PIN:"Consultez votre courrier électronique pour obtenir un code PIN",
    home_screen: "Accueil",
    home: "Accueil",
    in_progress: "En cours",
    completed: "Terminé",
    jobs_available: "Pas d'emplois disponibles",
    my_jobs: "Mes tâches",
    mission:'Mission',
    create_job: "Créer une tâche",
    logout:"Déconnexion",
    describe_your_service: "Décrivez votre service",
    select_service_type:"Sélectionnez un(des) service(s)",
    select_service: "Veuillez choisir un service ",
    select_timeline:"Sélectionnez la priorité",
    plumbing: "Plomberie",
    electrical: "Électrique",
    low_priority: "Faible priorité",
    high_priority: "Haute priorité",
    location: "Localisation",
    enter_location:"Entrez un emplacement",
    signed_in_successfully: "Vous êtes présentement connecté(e)",
    error:"Erreur",
    an_unexpected_error_occurred:"Une erreur inattendue s'est produite.",
    please_verify_your_email_before_logging_in: "Veuillez vérifier votre courriel",
    take_from_your_gallery:"Choisissez de votre galerie",
    job_description:"Description de tâche",
    job_posted_successfully: "Votre tâche a été enregistré avec succès",
    modify_issue:"Modifier tâche",
    delete_issue: "Effacer tâche",
    logged_out:"Déconnecté",
    you_have_been_logged_out_successfully:"Vous avez été déconnecté avec succès",
    an_error_occurred_while_logging_out:"Une erreur s'est produite lors de la déconnexion",
    hi:"Bonjour",
    need_something:"Avez-vous besoin de réparer",
    fixed:"quelque chose?",
    categories:"Catégories",
    view_all: "Consulter la liste",
    cleaning: "Nettoyage",
    requests:"Demandes",
    accept:"Accepter",
    reject:"Refuser",
    professional_needed:"Profession Recherchée",
    created_on:"Créé le",
    status:"État",
    cancel:"Annuler",
    status_client: {
        open: "Ouvert",
        closed: "Fermé",
        "closed by client": "Fermé par le client",
        completed: "Terminé",
        pending: "En attente",
        reopened: "Reouvert",
        "in progress": "En cours",
    },
    attached_images: "Images jointes",
    no_image_attached: "Aucune image jointe pour le moment",
    assigned_professional: "Professionnel assigné",
    rating: "Évaluation",
    comment: "Commentaire",
    review: "Avis",
    no_description_provided:"Aucune description fournie",
    payment_method: "Méthode de paiement",
    visa_ending: "Visa se terminant par",
    language: "Langue",
    title: "Titre",
    image: "Image",
    badges_remaining: "Vous pouvez en sélectionner encore {{count}}",
    your_job_has_been_posted: "Bravo! Votre tâche a été soumise!",
    use_default_address: "Utiliser l'adresse du profil",
    enter_new_address: "Rentrez une nouvelle adresse",
    posting_your_job: "Publication de votre tâche en cours...",
    reopen: "Réouvrir",
    delete: "Supprimer",
    are_you_sure: "Êtes-vous certain de procéder à",
    this_issue: "Ce problème?",
    modify_issue_text: "Cela va cloner ce problème et créer un nouveau. Vous pouvez le trouver dans vos problèmes ouverts.",
    yes: "Oui",
    jobInProgressComment: "Ce problème est actuellement en cours. Pour toute modification ou mise à jour, veuillez contacter le professionnel assigné via la fonction de chat." ,
    no_requests_available: "Pas d'offres pour vos tâches encore.",
    select_language: "Sélectionner la langue",
    select_language_prompt: "Veuillez sélectionner la langue de votre choix:",
    settings:'Paramètres',
    edit_profile:'Modifier le profil',
    appearance:'Apparence',
    terms_and_conditions:'Termes et conditions',
    coming_soon: 'À venir',
    appearance_feature_message:'Cette fonctionnalité est en cours de développement! Vous pourrez choisir entre le mode clair et le mode sombre!',
    profile:'Profil',
    street:'Rue:',
    current_password: 'Mot de pass actuel',
    current_password_validated:'Mot de passe actuel validé. Vous pouvez maintenant définir un nouveau mot de passe.',
    new_password:'Nouveau mot de passe',
    validate:'Valider',
    save_changes:'Enregistrer les modifications',
    authentication_failed: "Échec d'authentification",
    profile_data_failed_loading:'Échec du chargement des données de profil.',
    success:'Succès',
    invalid_address: 'Adresse invalide. Veuillez saisir une adresse valide.',
    address_verified_successfully: 'Adresse vérifiée avec succès.',
    incorrect_password: 'Mot de passe incorrect',
    network_error: 'Erreur de réseau. Veuillez vérifier votre connexion et réessayer.',
    new_passwords_match_error:'Les nouveaux mots de passe ne correspondent pas.',
    validate_password_please:'Veuillez valider votre mot de passe actuel avant de le mettre à jour.',
    changes_saved:'Vos modifications ont été enregistrées.',
    profile_update_error:'Échec de la mise à jour du profil.',
    new_passwords_match:'Les mots de passe correspondent ✓',
    new_passwords_mismatch:"Les mots de passe ne correspondent pas ✗",
    current_password_error:'Le mot de passe actuel est incorrect.'

}

export {en, fr}