const en = {
    sign_in: "Sign In",
    sign_up: "Sign Up",
    first_name: "First Name",
    last_name: "Last Name",
    email: "Email",
    password: "Password",
    welcome: "Welcome to",
    change_language: "Change Language",
    forgot_password: "Forgot Password?",
    forgot_password_no_question_mark: "Forgot Password",
    do_not_have_an_account: "Don't have an account? Sign up",
    back: "Back",
    valid_address: "Please enter a valid email address",
    confirm_password: "Confirm Password",
    next: "Next",
    street_address: "Street Address",
    postal_code: "Postal Code",
    verify_address: "Verify Address",
    already_have_an_account:"Already have an account? Sign in",
    valid_address_entered:"Valid Address entered",
    send_reset_pin: "Send Reset PIN",
    enter_pin: "Enter PIN",
    Check_email_for_PIN:"Check your email for a PIN to reset your password",
    home_screen: "Home Screen",
    in_progress: "In Progress",
    completed: "Completed",
    jobs_available: "No jobs available",
    my_issues: "My Issues",
    mission: 'Jobs',
    create_issue: "Create new Issue",
    logout: "Logout",
    describe_your_service: "Describe your service",
    select_service_type: "Select Service Type",
    select_service: "Select Service",
    select_timeline:"Select Timeline",
    plumbing: "Plumbing",
    electrical: "Electrical",
    low_priority: "Low Priority",
    high_priority: "High Priority",
    location:"Location",
    enter_location:"Enter Location",
    signed_in_successfully:"Signed in successfully",
    error:"Error",
    an_unexpected_error_occurred: "an unexpected error occurred",
    please_verify_your_email_before_logging_in: "Please verify your email before logging in",
    take_from_your_gallery: "Take from your gallery",
    job_description:"Job Description",
    job_posted_successfully: "Job posted successfully",
    modify_issue: "Modify Issue",
    delete_issue: "Delete Issue",
    logged_out: "Logged out",
    you_have_been_logged_out_successfully:"you have successfully logged out successfully",
    an_error_occurred_while_logging_out:"an error occurred while logging out",
    hi:"Hi",
    need_something:"Need Something?",
    fixed:"fixed?",
    categories:"Categories",
    view_all: "View All",
    cleaning:"Cleaning",
    requests:"Requests",
    accept:"Accept",
    reject:"Reject",
    professional_needed:"Professional Needed",
    created_on:"Created On",
    status:"Status",
    cancel:"Cancel",
    status_client: {
        open: "Open",
        closed: "Closed",
        "closed by client": "Closed By Client",
        completed: "Completed",
        pending: "Pending",
    },
    attached_images: "Attached Images",
    no_image_attached: "No image attached yet",
    assigned_professional: "Assigned Professional",
    rating: "Rating",
    comment: "Comment",
    review: "Review",
    no_description_provided:"No description provided",
    payment_method: "Payment Method",
    visa_ending: "Visa ending in",
    language: "Language",
}

const fr = {
    sign_in: "Se connecter",
    sign_up: "S'inscrire",
    first_name: "Prénom",
    last_name: "Nom de Famille",
    email: "Courriel",
    password: "Mot de Passe",
    welcome: "Bienvenue à",
    change_language: "Changer La Langue",
    forgot_password: "Oubli du mot de passe?",
    forgot_password_no_question_mark: "Mot de passe oublié",
    do_not_have_an_account: "Si vous n'avez pas encore de compte, créez-en un",
    back: "Retourner",
    valid_address:"Veuillez indiquer une adresse de courriel valide",
    confirm_password: "Confirmer le mot de passe",
    next: "Suivant",
    street_address: "Adresse Civique",
    postal_code: "Code Postal",
    verify_address: "Vérifier l'adresse",
    already_have_an_account:"Vous êtes déjà inscrit? Se connecter",
    valid_address_entered:"Une adresse de courriel valide",
    send_reset_pin: "Rétablissez le PIN",
    enter_pin:"Entrer un code PIN",
    Check_email_for_PIN:"Consultez votre courrier électronique pour obtenir un code PIN",
    home_screen: "Accueil",
    in_progress: "en cours",
    completed: "Terminé",
    jobs_available: "pas des travail libres",
    my_issues: "Mes Tâches",
    mission:'mission',
    create_issue: "Créer une tache",
    logout:"Déconnexion",
    describe_your_service: "Décrivez votre service",
    select_service_type:"Sélectionnez un(des) service(s)",
    select_service: "Veuillez choisir un service ",
    select_timeline:"Sélectionnez la chronologie",
    plumbing: "Plomberie",
    electrical: "Électrique",
    low_priority: "faible priorité",
    high_priority: "haute priorité",
    location:"Site",
    enter_location:"Entrez un emplacement",
    signed_in_successfully: "Vous êtes présentement connecté(e)",
    error:"Erreur",
    an_unexpected_error_occurred:"Une erreur inattendue s'est produite.",
    please_verify_your_email_before_logging_in: "Veuillez vérifier votre adresse email",
    take_from_your_gallery:"Prenez de votre galerie",
    job_description:"description de tache",
    job_posted_successfully: "Tache être enregistré avec succès",
    modify_issue:"modifier tache",
    delete_issue: "effacer tache",
    logged_out:"Déconnecté",
    you_have_been_logged_out_successfully:"Vous avez été déconnecté avec succès",
    an_error_occurred_while_logging_out:"une erreur s'est produite lors de la déconnexion",
    hi:"Bonjour",
    need_something:"Cherchez de quelque chose?",
    fixed:"fixé(e)?",
    categories:"Catégories",
    view_all: "Consulter la liste",
    cleaning: "Nettoyage",
    requests:"Demandes",
    accept:"Accepter",
    reject:"Refuser",
    professional_needed:"Profession Recherché",
    created_on:"Créé le",
    status:"État",
    cancel:"Annuler",
    status_client: {
        open: "Ouvert",
        closed: "Fermé",
        "closed by client": "Fermé par le client",
        completed: "Terminé",
        pending: "En attente",
    },
    attached_images: "Images jointes",
    no_image_attached: "Aucune image jointe pour le moment",
    assigned_professional: "Professionnel assigné",
    rating: "Évaluation",
    comment: "Commentaire",
    review: "Avis",
    no_description_provided:"Aucune description fournie",
    payment_method: "Méthode de paiement",
    visa_ending: "Visa se terminant par",
    language: "Langue",
}

export {en, fr}