name: CI

on:
  workflow_dispatch:
  pull_request:
    branch: [main]

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  professionalClient:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          cache: 'npm'
          cache-dependency-path: professionalClient/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: professionalClient

      - name: Run Jest Tests
        run: npx jest
        working-directory: professionalClient
        continue-on-error: true

      - name: Jest Annotations & Coverage
        uses: ArtiomTr/jest-coverage-report-action@262a7bb0b20c4d1d6b6b026af0f008f78da72788 # v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: professionalClient
          continue-on-error: true

      - name: Publish CTRF Suite Folded Summary
        run: npx github-actions-ctrf suite-folded professionalClient/ctrf/ctrf-report.json
        if: always()

      - name: Publish CTRF Pull Request Comment
        run: npx github-actions-ctrf pull-request professionalClient/ctrf/ctrf-report.json
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fixerClient:
    runs-on: ubunt-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          cache: 'npm'
          cache-dependency-path: fixerClient/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: fixerClient

      - name: Run Jest Tests
        run: npx jest
        working-directory: fixerClient
        continue-on-error: true

      - name: Jest Annotations & Coverage
        uses: ArtiomTr/jest-coverage-report-action@262a7bb0b20c4d1d6b6b026af0f008f78da72788 # v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: fixerClient
          continue-on-error: true

      - name: Publish CTRF Suite Folded Summary
        run: npx github-actions-ctrf suite-folded fixerClient/ctrf/ctrf-report.json
        if: always()

      - name: Publish CTRF Pull Request Comment
        run: npx github-actions-ctrf pull-request fixerClient/ctrf/ctrf-report.json
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8.2.1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          working-directory: fixerClient  # Explicitly point to fixerClient

      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8.2.1
        with:
          command: eas update --auto --branch ${{ github.event.pull_request.head.ref }}
          working-directory: fixerClient  # Explicitly point to fixerClient

      - name: Moropo - Trigger Mobile App Test Run
        uses: moropo-com/action-trigger-test-run@ce1e0c934337f198741c5c96b2e81aa8fb3ce942 # v2.0.9
        with:
          api_key: ${{ secrets.MOROPO_API_KEY }}
          scheduled_test_id: ee71749e-a0b6-4620-bcbc-74ee02353c5e
          sync: true
          expo_release_channel: https://u.expo.dev/2946827b-9037-4f1b-866f-9dd9ea93edab?channel-name=${{ github.event.pull_request.head.ref }}&runtime-version=1.0.0&platform=android
